### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by matkuki** [inv2004/ccal#1] opened 2023-12-24 23:09 UTC
- Windows 10 x64
- Nim 2.0.2

There seems to be an alignment issue caused by a double print in October:
![image](https://github.com/inv2004/ccal/assets/10289651/bd1c99fe-2bd2-4d72-93d0-53ba761a798c)
I also tried `ccal SI 2023` and the same double print occurs in Octorber.

**Comment by inv2004** [comment] 2023-12-26 15:45
Just noticed, is it powershell? Let me try in PS. Was not able to reproduce it in linux

**Comment by matkuki** [comment] 2023-12-26 15:49
Yes, but it's the same in a normal `Console`:
![image](https://github.com/inv2004/ccal/assets/10289651/1095eed8-ed72-4199-92a1-fbca19c8ec8d)

**Comment by inv2004** [comment] 2023-12-26 21:29
checked in cmd and PS, unfortunately did not reproduce it.

Could you please help me to debug it, maybe just to replace " " with commas on the lines 50 and 52 https://github.com/inv2004/ccal/blob/main/src/ccal.nim#L50

**Comment by matkuki** [comment] 2023-12-26 22:36
![image](https://github.com/inv2004/ccal/assets/10289651/fdeb8fe8-ba6e-4158-8332-009b3e3eccba)

**Comment by inv2004** [comment] 2023-12-28 22:49
I suppose that the reason could be summer-time shift in your timezone for the date or, maybe, leap second

can you please before and _after_ the line https://github.com/inv2004/ccal/blob/main/src/ccal.nim#L73
add `echo dt`
then compile
and run `ccal 2024 SI | grep 2024-10-27`

It should show two rows - would be interesting to check them

Thank you,

**Comment by inv2004** [comment] 2023-12-28 22:56
@matkuki 
I think I simulated it via `export TZ=Europe/Ljubljana`. Please ignore prev message (deleted)

**Comment by inv2004** [comment] 2023-12-28 23:06
Should be fixed here: https://github.com/inv2004/ccal/commit/f152d399a51d79e8c24556234236ba16752441a5

Please update to the last version and thank you for the report

**Comment by matkuki** [comment] 2024-01-02 17:07
Thanks @inv2004 
The original problem is fixes, yes, but now there is a color issue on Windows:
![image](https://github.com/inv2004/ccal/assets/10289651/95f891ca-79fe-4624-a322-ebbf59e7d059)
If I select the text, only then it's visible (the screenshots are in PowerShell, the same goes for the normal Windows Console):
![image](https://github.com/inv2004/ccal/assets/10289651/8b850b7d-f143-40fd-81b5-d08ad007bfed)

**Comment by inv2004** [comment] 2024-01-03 00:12
@matkuki 
It is a bit strange, but looks like windows default terminal color is black.

Fixed here: https://github.com/inv2004/ccal/commit/15eb33e9b186e7649e98946e67ea8c9a709b7b7a

**Closed as completed** 2024-01-03 12:21 UTC

**Comment by matkuki** [comment] 2024-01-03 12:45
Thanks, confirming that it looks correct now 👍
